server:
  port: 8001
spring:
  application:
    name: service-edu
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/guli?serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
   db-config:
    logic-delete-field: flag  #全局逻辑删除字段值 3.3.0开始支持，详情看下面。
    logic-delete-value: 1 # 逻辑已删除值(默认为 1)
    logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  mapper-locations: classpath:com/atguigu/eduservice/mapper/xml/*.xml

logging:
  level:
    com.atguigu.eduservice.client.*: debug
#ribbon:
#  ReadTimeout: 60000
feign:
  hystrix:
    enabled: true
#  ConnectTimeout: 60000

#
#wx:
#  open:
#    appid: wxed9954c01bb89b47
#    appsecret: a7482517235173ddb4083788de60b90e
#    redirecturl: http://guli.shop/api/ucenter/wx/callback