server:
  port: 8003
spring:
  application:
    name: service-vod
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
aliyun:
  vod:
    file:
      keyid: LTAI4G7TCBoWWLUTfwKxKt4E
      keysecrer: APZrJCUi4uHmi2jIFyqjFcpc44eTFb