server:
  port: 8007
spring:
  application:
    name: service-order
  cloud:
    nacos:
      discovery:
        server-addr: localhost
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 123456
    username: root
    url: jdbc:mysql://localhost:3306/guli?serverTimezone=GMT%2B8
mybatis-plus:
  mapper-locations: classpaht:com/atguigu/eduorder/mapper/xml/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      exection:
        isolation:
          thread:
            timeoutInMilliseconds: 3000
#logging:
#  level: