server:
  port: 8009
spring:
  application:
    name: service-acl
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guli?serverTimezone=GMT%2B8
    password: 123456
    username: root
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH-mm-ss
mybatis-plus:
  mapper-locations: classpath:com/atguigu/eduservice/mapper/xml/*.xml