server:
  port: 8005

spring:
  application:
    name: service-msm
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/guli?serverTimezone=GMT%2B8
  redis:
    host: localhost
    port: 6379
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 5
        min-idle: 0