server:
  port: 8008
spring:
  application:
    name: service-statistics
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/guli?serverTimezone=GMT%2B8
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH-mm-ss
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

mybatis-plus:
  mapper-locations: classpath:com\atguigu\statistics_daily\mapper\xml\*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl